name: code
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 3.0.21+124474

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  collection: ^1.18.0
  jitsi_meet_wrapper: ^0.2.0+1
  syncfusion_localizations: ^24.1.41
  cupertino_icons: ^1.0.6
  kiwi: ^4.1.0
  rxdart: ^0.27.7
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  image_gallery_saver: ^2.0.3
  mime: ^1.0.4
  http: ^1.1.2
  dio: ^5.4.0
  file_picker: ^6.1.1
  flutter_slidable: ^3.0.1
  device_info_plus: ^9.1.1
  android_id: ^0.3.6
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.2
  devicelocale: ^0.7.0
  fluttertoast: ^8.2.4
  permission_handler: ^11.1.0
  photo_view: ^0.14.0
  scrollable_positioned_list: ^0.3.8
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  flutter_parsed_text: ^2.2.1
  web_socket_channel: ^2.4.1
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^5.0.2
  share_plus: ^7.2.1
  open_filex: ^4.3.4
  uuid: ^4.3.1
  image_cropper: ^5.0.1
  percent_indicator: ^4.2.3
  multi_image_picker2: ^5.0.2
  flutter_svg: ^2.0.9
  flutter_emoji: ^2.5.1
  emoji_picker_flutter: ^1.6.3
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_analytics: ^10.7.4
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.2.0
  keyboard_actions: ^4.2.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  android_external_storage: ^0.1.0
  sqflite: ^2.3.0
  audioplayers: ^5.2.1
  vibration: ^1.8.4
  another_audio_recorder: ^1.1.0
  timeline_tile: ^2.0.0
  syncfusion_flutter_calendar: ^24.1.41
  syncfusion_flutter_datepicker: ^24.1.41
  flutter_speed_dial: ^7.0.0
  flash: ^3.1.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  flutter_image_compress: ^2.1.0
  uni_links: ^0.5.1
  intl_phone_number_input: ^0.7.4
  otp: ^3.1.4
  mobile_scanner: ^3.5.5
  base32: ^2.1.3
  flutter_callkit_incoming: ^2.0.0+2
  flutter_colorpicker: ^1.0.3
  flutter_app_badger: ^1.5.0
  youtube_player_iframe: ^4.0.4

  receive_sharing_intent:
    git:
      url: https://github.com/dilankayapagit/receive_sharing_intent.git

  flutter_html: ^3.0.0-beta.2

  record: ^5.0.4

dependency_overrides:
  uuid: ^4.3.1
  web: ^0.4.0 
  meta: ^1.11.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/_res/assets/
    - lib/_res/assets/img/
    - lib/_res/assets/img/reactions/
    - lib/_res/assets/img/activities/
    - lib/_res/assets/img/sessions/
    - lib/_res/assets/img/themes/
    - lib/_res/assets/countries.json
    - lib/_res/assets/paises.json
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: EmojiOne
      fonts:
        - asset: lib/_res/assets/fonts/EmojiOneColor.otf
    - family: SourceSansPro
      fonts:
        - asset: lib/_res/assets/fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: lib/_res/assets/fonts/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/_res/assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: lib/_res/assets/fonts/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/_res/assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: lib/_res/assets/fonts/SourceSansPro-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/_res/assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: lib/_res/assets/fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/_res/assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: lib/_res/assets/fonts/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/_res/assets/fonts/SourceSansPro-Black.ttf
          weight: 900
        - asset: lib/_res/assets/fonts/SourceSansPro-BlackItalic.ttf
          weight: 900
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
