on:
  push:
    branches:
    - mobile
    - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17.x'
        cache: gradle

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.5'
        # channel: "stable"
        cache: true

    - run: flutter pub get
    - run: flutter build appbundle --target=lib/main_prod.dart 
    - run: flutter build apk --release --target=lib/main_prod.dart 
    
    - name: Push to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/*,build/app/outputs/bundle/release/*,build/web.zip"
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.TOKEN }}

    # - name: Publish in play store
    #   uses: r0adkll/upload-google-play@v1
    #   with:
    #     serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
    #     packageName: com.japonesafondo.aprende_japones_kana
    #     releaseFiles: build/app/outputs/bundle/release/app-release.aab
    #     track: internal
    #     status: completed
    #     changesNotSentForReview: false
    #     token: ${{ secrets.TOKEN }}
        
